### ISSUE TITLE
HTTPS flag?

### ISSUE THREAD

**Issue by alexkwolfe** [moll/node-mitm#10]
The readme says "Please note that HTTPS requests are currently "morphed" into HTTP requests. That's to save us from having to set up certificates and disable their verification."

Could you conceivably add a flag to the request object that would indicate that the protocol was https?

**Comment by holic** [comment]
:+1:

**Comment by papandreou** [comment]
Just ran into this as well. I recommend `req.{connection,socket}.encrypted` like node.js itself uses.

**Comment by vvo** [comment]
:+1: @moll Do you think we can merge this?

**Comment by moll** [comment]
Hey! Late to party as always. :innocent: 

Thanks for the suggestion! I combined your and @papandreou's proposal with using the actual `Tls.TLSSocket`. Now, both the client side socket and the server side socket should be instances of `TLSSocket`s with the `encrypted` and `authorized` flags set. Underneath they're still plain `Net.Socket` objects.

Anywho, all that's in v1.1.0 available from any well stocked retail store near you.

**Comment by holic** [comment]
Thanks @moll !
