### ISSUE TITLE
socket.write is synchronous

### ISSUE THREAD

**Issue by gustavnikolaj** [moll/node-mitm#22]
I would expect the following code, to output:

```
wrote foo
got bar
```

but it outputs:

```
got bar
wrote foo
```

```js
var Mitm = require('mitm');
var mitm = Mitm();
mitm.on('connection', function (socket) {
    socket
    .on('connect', function () {
        socket.write('foo');
        console.log('wrote foo');
    })
    .on('data', function (chunk) {
        console.log('got', chunk.toString());
    });
});

var socket = require('net').connect(42, 'foobar.com')
socket.on('data', function () {
    socket.write('bar');
});
```

I think it's very unexpected that `write` calls it callback synchronously. That is not how it usually works... When working with sockets, at least a tick would go by, before the callback was processed :-)

**Comment by gustavnikolaj** [comment]
cc @papandreou

**Comment by moll** [comment]
Thank you for reporting this and sorry for the long wait! This will be in the next release — merged @mwoc's PR and added a few tests to ensure they catch the sync case should someone refactor the code. ;)

**Comment by moll** [comment]
Would you mind giving it a test, @gustavnikolaj, to confirm it all works as expected? You can install from this repo directly. I'll then release a new version. Thanks!

**Comment by gustavnikolaj** [comment]
I would love to, but I can't until next week. I'm on vacation at the moment
(without a laptop) :-) I'll get back to you as soon as possible.

Den mandag den 21. marts 2016 skrev Andri Möll <notifications@github.com>:

**Comment by gustavnikolaj** [comment]
@moll I can confirm that it's fixed when using the current tip of the master branch :-) :+1:
