### ISSUE TITLE
Additional properties to response

### ISSUE THREAD

**Issue by G07cha** [moll/node-mitm#27]
I can't find how to set custom body for http response, for example if use `res.write` or `res.end` functions it will set only message property, how do I define other response properties?

**Comment by moll** [comment]
Which properties do you have in mind? Through HTTP you can send both headers with `res.setHeader("X-Foo", "123")` or body, with `res.write`.

**Comment by G07cha** [comment]
@moll I would like to send something like {"foo": "bar"} in body, but as I know `res.write` allow only `string` or `buffer` argument types.

**Comment by moll** [comment]
Yep. That's because HTTP, the underlying protocol, is text based.

You'll have to do this:
```js
res.setHeader("Content-Type", "application/json")
res.end(JSON.stringify({name: "John"})
```

I don't know what's the best resource for reading more about HTTP and its idioms, but perhaps you're better at finding that out. ;)

**Comment by G07cha** [comment]
Thank you a lot, it's shame for me to don't know such fundamentals, I'm try to correct this as soon as possible, thanks again!

**Comment by moll** [comment]
You're welcome.
