### ISSUE TITLE
Could you add support for TLS socket

### ISSUE THREAD

**Issue by talamaska** [moll/node-mitm#3]
This is very nice module, but it limits to non-secure tcp connections. Could you add support for TLS socket, as it is the workaround for secure tcp sockets

**Comment by papandreou** [comment]
As a side point, it seems like the fact that a client cert is used is discoverable when mitm'ing an https request, as the second argument passed to `connect` and `connection` listeners will contain an `agent` property which in turn has the `cert`, `key`, and `ca` properties. That'll help me test that some of my code is connecting using the correct client cert.

**Comment by moll** [comment]
I'll close this for now as there's nothing actionable here, but we can continue discussing. If there's something Mitm can directly make easier when testing TLS connections, please let me know!
