### ISSUE TITLE
which port does it listen?

### ISSUE THREAD

**Issue by zszszsz** [moll/node-mitm#30]
and can I change this?

**Comment by zszszsz** [comment]
actually i am trying to use this as http/https mitm proxy

**Comment by moll** [comment]
Mitm.js hooks into Node.js in its outgoing TCP connection layers, so no real TCP connections are invovled. You could get the sent data and proxy it to another real host I imagine. You'd have to ensure you call `bypass` (an example is in the README) on the real host when proxying, though!

**Comment by moll** [comment]
By no real TCP connections I mean it captures everything — every host, every port.

**Comment by zszszsz** [comment]
thanks a lot for pointing out my misunderstanding of this project

**Comment by zszszsz** [comment]
so it is the mitm of all the node scripts running instead of all the processes of the machine, which means it can not be the mitm of the browser, have I got it right?

**Comment by moll** [comment]
Yep. It intercepts connections only from within the same Node.js process its running in. It's mostly a tool for testing JavaScript.

**Comment by moll** [comment]
Anything else I can help with?

**Comment by zszszsz** [comment]
thank you very much.
I was afk several days ago  and sorry for not replying that(>_<)
