### ISSUE TITLE
How to get the request payload?

### ISSUE THREAD

**Issue by jac0117** [moll/node-mitm#32]
I need to capture the payload from the request. I'm intercepting calls to LDAP. The *opts* variable only contains *host* and *port*. Is there a way to capture the payload?

**Comment by moll** [comment]
Hey!

The way TCP works in Node is that it's a stream you need to read from to get the bytes.

Does https://github.com/moll/node-mitm#intercepting-tcp-connections shine light in the right direction? The server object Mitm.js returns works exactly like a regular TCP server documented at https://nodejs.org/api/net.html.

**Comment by jac0117** [comment]
Thanks for the info. I was able to get it.

One more thing, when you call socket.bypass(), it seems it doesn't let the request proceed to the original destination (which is not localhost). Is that the case? Is that how to module works? Or is there a way I can let a tcp request proceed to the actual destination? I noticed in your docs you mentioned you can use bypass() to forward it to the original destination (but it's not working for me). I assume it's only for localhost?

**Comment by moll** [comment]
Are you doing something like the example in https://github.com/moll/node-mitm#bypassing-interception and it's still not getting through? Would you mind sharing that piece of code? It should definitely allow the original request to go through.

**Comment by jac0117** [comment]
Theoretically, bypassing every connection should allow my application to run as normal, but it just ends up hanging.

var ldapInterceptor = require("mitm")();
ldapInterceptor.enable();

ldapInterceptor.on('connection', function (socket, opts) {
	socket.bypass();
});

I also tried inside the 'connection' event callback:
	socket.on('data', function(data) {
		socket.bypass();
	});

**Comment by moll** [comment]
I suspect this could be because you're calling `bypass` in the `connection` event and not in the `connect` event. Sorry, they are similarly named, but happen at two different times in the lifecycle.

**Comment by moll** [comment]
Can I close this or is there anything else, @jac0117?

**Comment by jac0117** [comment]
Yes

**Comment by moll** [comment]
Love the single answer to a disjunctive question. :D
