### ISSUE TITLE
mitm

### ISSUE THREAD

**Issue by roccomuso** [moll/node-mitm#41]
isn't the MITM name misleading? we're analyzing packets, not doing any ARP poisoning.

**Comment by moll** [comment]
If you squint enough, there is a _thing_ between the client and server that could intercept [network] packets. ARP poisoning is just one tactic to interject oneself between the client and server. Mitm.js's focus is on in-process use and thereby interjects itself through regular language features. ;)

**Comment by moll** [comment]
I'll close this as there's nothing particularly actionable here beyond philosophizing over semantics. :)
