### ISSUE TITLE
Breaks with node.js 11.8.0:  [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined

### ISSUE THREAD

**Issue by papandreou** [moll/node-mitm#56]
Updating node from 11.7.0 to 11.8.0 makes my tests and the node-mitm test suite fail with:

```
     Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined
      at validateNumber (internal/validators.js:130:11)
      at Object.getSystemErrorName (util.js:394:3)
      at errnoException (internal/errors.js:363:21)
      at Socket._final (net.js:368:25)
      at callFinal (_stream_writable.js:617:10)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

The answer must be buried somewhere in https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#11.8.0

**Comment by moll** [comment]
Ugh. I'm worried eventually the popularity of ES6 within Node will forbid Mitm's hooking entirely. Hopefully not yet at least. Thanks for bringing v11.8 probs up though! Makes me happy I personally stick to ancient LTS versions of software — I'm seldom affected by such constant changes. :P

**Comment by moll** [comment]
Fixed it. I'll push in a sec, see if it works fine on all Node versions and then publish a release.

**Comment by moll** [comment]
Mitm.js v1.6 is live! Please give it a spin and report back if it's not working. Thanks again for the heads-up!

**Comment by papandreou** [comment]
Thanks a lot! That was some fast action 💪🏻
