### ISSUE TITLE
node 10.15.1: TypeError: this._handle.shutdown is not a function

### ISSUE THREAD

**Issue by papandreou** [moll/node-mitm#57]
Here we go again. Upgrading from node.js 10.15.0 to 10.15.1 causes error in my test suite:

```
     Uncaught TypeError: this._handle.shutdown is not a function
      at Socket._final (net.js:361:26)
      at callFinal (_stream_writable.js:612:10)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

It can also be reproduced with the node-mitm test suite, 4 tests fail like that.

**Comment by moll** [comment]
Thx. On it!

**Comment by moll** [comment]
I'll have to wait a little for https://www.archlinux.org/packages/community/x86_64/nodejs-lts-dubnium/ to reach mirrors before I could verify my fix (which would probably be merely revealing the existing `shutdown` function to Node v10.5.1).

**Comment by moll** [comment]
Threw Mitm v1.7 up with support for Node v10.15.1.
