### ISSUE TITLE
Relicensing?

### ISSUE THREAD

**Issue by th-ch** [moll/node-mitm#61]
Hey @moll, thanks for creating this awesome library! 

We would like to use it in a company project but the AGPL license prevents us from using it at the moment (the terms of the AGPL state that every software using it should also be under the AGPL, which is a blocker for us).

Is relicensing this project under a more permissive license (e.g. MIT license) something you would consider?

**Comment by moll** [comment]
Hey,

Fortunately all of my OSS projects come with the same clause as LGPL does (https://github.com/moll/node-mitm/blob/master/LICENSE#L8), that is, mere use of this lib does _not_ require you to license other work under AGPL. The summary in the README (https://github.com/moll/node-mitm#license) was meant to signal that, too. :)

**Comment by moll** [comment]
I take it you had no objection to what I said above and forgot to close the issue. :) Feel free to open let me know if you had comments.
