### ISSUE TITLE
License mismatch between LICENSE file and package.json

### ISSUE THREAD

**Issue by fredrikcarlbom** [moll/node-mitm#79]
Since `LICENSE` mentions "GNU Affero General Public License" but nothing about Lesser I read it as this code is covered by the AGPL v3.0 license but the `package.json` file states LAGPL which is not the same license. This makes it hard for non open-source projects to use this package.

**Comment by moll** [comment]
Hey! Thanks for caring about open source licensing. The "Lesser" part arises from that paragraph:

> Additional permission under the GNU Affero GPL version 3 section 7:
> If you modify this Program, or any covered work, by linking or
> combining it with other code, such other code is not for that reason
> alone subject to any of the requirements of the GNU Affero GPL version 3.

That's the same addition that the [Lesser GPL adds](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL). Does that clarify things for you?

**Comment by fredrikcarlbom** [comment]
> That's the same addition that the [Lesser GPL adds](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL). Does that clarify things for you?

That explains it, thank you!
